default_platform(:ios)

platform :ios do
  SCHEME = "weg-li"

  desc "Build and run tests"
  lane :test do
    scan(
      scheme: SCHEME,
      device: 'iPhone 13',
      result_bundle: true,
      clean: true
    )
    end
end
